- sopel_modules/twitter/twitter.py
Twitter has moved away from the classic 140-character limit in recent years. Considerably longer tweets are possible, especially if one counts attached media, links, & `@` mentions that might be excluded from the calculated text length. If we ask for "extended" tweet mode, we can display the full text!
I adapted the try/except thing from my personal copy of `twit.py`, forked from sopel-extras. Older tweets might still return JSON without the `full_text` key, if memory serves (it's been a while). At any rate, the cost of checking for an exception is minimal, far outweighed by the benefits of catching one if some old tweet link returns an outdated data layout.
> Support >140 character tweets without truncation

- NEWS
- README.md
- requirements.txt
- setup.py
- sopel_modules/twitter/__init__.py
- sopel_modules/twitter/twitter.py
* Updated readme
* Backfilled NEWS file with prior versions' changes
* Fixed deprecated Python syntax
* Tightened up requirements
This is one of the few "official" plugins maintained by the Sopel org on GitHub that already used the URL decorator despite its issues in older Sopel releases (i.e. not working if the `url` module was disabled).
> Overhaul for Sopel 7

- sopel_modules/twitter/twitter.py
Someone please eliminate this false `full_text`/`text` dichotomy from the Twitter API.
> twitter: fix some quoted tweets causing errors

- sopel_modules/twitter/twitter.py
Builds on (well, forks off of) #4; opening as draft for now. Will need to rebase later.
Current to-do list:
- Currently, any expanded media URLs that cannot be found in the tweet body as short links are just added to the end of the message
- This places extra links after the tweet stats, and after the quoted tweet (if any)
- i.e. build the original tweet, quoted tweet (if it exists), and stats separately, then combine them (still thinking about the best way to do this)
> Refactor tweet output: media URL expansion, quoted tweet changes

- sopel_modules/twitter/twitter.py
This should be stable, even if the details provided for a profile in the code at time of PR opening are currently minimal. Including more information is planned; see below.
```
<dgw>        https://twitter.com/hidgw
<SopelTest>  [Twitter] dgw (@hidgw) | 724 friends, 1,355 followers | 30,665 tweets, 12,100 ♥s
```
Checklist of stuff to output:
- Twitter uses `t.co` for these, so they'll have to be expanded… 🙁
- ^ Fortunately, the user object also includes the required entity data
- These can be up to 160(?) characters; should probably be output last to allow for truncation
> Handle profile links

- sopel_modules/twitter/twitter.py
I created this feature branch on my last day in the office before we stopped going in for COVID-19.
Super happy that my past self pushed it up to GitHub; my office desktop doesn't have remote access, and no one has _ever_ said, "Designing that regex will be even _more_ fun the second time!"
So, though I forgot about it for a couple weeks, the testing can continue now.
> twitter: Handle tweet URLs of the `/i/web/status` form

- sopel_modules/twitter/twitter.py
Tightening the regex to match either ONLY a user, or a user AND status ID, should reduce instances of the bot saying "Twitter returned an error" at random links that happen to contain `twitter.com` but aren't one of the kinds we handle.
Could have just fixed this in the actual code, and ignored matches with username 'i' and no status ID, but Twitter *could* allow someone to register that name in the future.
> Avoid matching e.g. `/i/events/1234567890` as a link to i's user profile

- sopel_modules/twitter/twitter.py
If quoted tweet link appears before media link in raw tweet text, the quoted tweet URL replacement using `\s*` would gobble up the whitespace between the tweet text and media link.
> Fix quoted tweets messing up presentation of media links

- sopel_modules/twitter/twitter.py
`m.` redirects to `mobile.` and might never actually be in a link, but it's no big deal to include it too.
Note: Need to put this through some more rigorous regex tests before merging/releasing.
> Add Twitter's mobile subdomains for URL handling

- sopel_modules/twitter/twitter.py
If a quoted tweet is deleted, `tweet` does not contain `quoted_status` and the bot currently prints an exception to the channel.
> Don't attempt to post deleted QTs

- sopel_modules/twitter/twitter.py
The plugin currently does not correctly handle some twitter-generated links like `https://twitter.com/NASA?lang=en` ("User not found") or some user-generated links like `https://twitter.com/NASA/` (note trailing slash: doesn't match at all).
Current regex:
New regex:
> users: handle trailing get vars and slashes

- sopel_modules/twitter/twitter.py
It's probably better to explicitly match the full URL for non-status stuff?
Also added fxtwitter.com support while I'm mucking with regexes :shushing_face:
Addl test cases:
```
https://twitter.com/i/web/status/1514372885758025728
https://twitter.com/i/web/status/1514372885758025728/
https://twitter.com/i/web/status/1514372885758025728?s=20
https://twitter.com/i/web/status/1514372885758025728/?s=20
https://twitter.com/i/?s=20
https://twitter.com/i/status/1514372885758025728/?s=20
https://fxtwitter.com/NASA/status/1514372885758025728/?s=20
```
Fixes #32
> Fix `/i/web/status/n` links

- sopel_modules/twitter/twitter.py
Example: https://twitter.com/NASAWebb/status/1545413807996129280
Current: `< Sopel> [Twitter] NASA Webb Telescope (@NASAWebb): 🎯 Target(s) acquired!   ⏎  ⏎ The targets of Webb’s first images have been announced: https://go.nasa.gov/3ysrC73 ⏎  ⏎ ✨ SMACS 0723  ⏎  ⏎ ✨ WASP-96b  ⏎  ⏎ ✨ Southern Ring Nebula  ⏎  ⏎ ✨ Stephan’s Quintet  ⏎  ⏎ ✨ Carina Nebula  ⏎  ⏎ Tune in July 12 as we reveal Webb’s first images & #UnfoldTheUniverse. https://pbs.twimg.com/media/FXJpp-XX0AAhLuj.jpg | 2621 RTs | 10159 ?`
Proposed: `< Sopel> [Twitter] NASA Webb Telescope (@NASAWebb): 🎯 Target(s) acquired! ⏎ The targets of Webb’s first images have been announced: https://go.nasa.gov/3ysrC73 ⏎ ✨ SMACS 0723 ⏎ ✨ WASP-96b ⏎ ✨ Southern Ring Nebula ⏎ ✨ Stephan’s Quintet ⏎ ✨ Carina Nebula ⏎ Tune in July 12 as we reveal …
> collapse whitespace with 1+ newline to one newline

- sopel_modules/twitter/twitter.py
`sopel.logger.get_logger()` is deprecated.
> Use the proper way of getting a plugin logger

- README.md
- setup.cfg
- sopel_twitter/__init__.py
Who needs to migrate to Twitter's annoying _and_ (now) expensive v2 API (#23) when you can just use `tweety-ns`?
I have tested a sampling of Tweet and profile links chosen from my "home timeline" (which is as likely as not now to show tweets from people I've never followed, or even interacted with at all), containing pictures, GIFs, videos, and quoted tweets. So far as I can tell, this rewrite is one-for-one feature-complete vs. the old code using Twitter API v1 directly. It's also being tested in #sopel at Libera (not that we frequently post Twitter links there).
_The history here is very messy to start, because the `tweety-ns` package had a few show-stopping bugs as of early February that made me halt the rewrite for several weeks—but I definitely wanted a record of the original rewrite …
> Migrate to Tweety for data fetch

- sopel_twitter/__init__.py
Seems that keeping a Tweety instance around for too long doesn't work. It'll eventually start failing to fetch tweets. Probably some secret involved that's time-derived.
Not knowing the "safe" time interval to keep using a single Tweety instance, I have chosen the nuclear option: No optimization at all. (In the future I might implement some smart-retry logic to cache a Tweety instance but replace it with a fresh one before erroring, but let's see if the performance hit is big enough to warrant that work.)
> Construct new Tweety instance for each tweet

- README.md
- setup.cfg
- sopel_twitter/__init__.py
Lots of stuff changed this week, breaking the old library version AND adding required authentication to fetch any data on the new endpoints. Cookies are now required.
Recommending that people do not use credentials for their main Twitter account out of an abundance of caution; one never knows the possible consequences of associating an account you actually care about with a tool like this.
> Rework to function with cookies & update to tweety-ns 0.8

- README.md
- setup.cfg
- sopel_twitter/__init__.py
~~Cookies aren't required any more.~~ The mechanism to use cookies has changed. Username/password support is also available, so let's use that instead.
I'm positive some optimization could be done here to make the plugin work faster, but it's *functional* with the latest library version.
More to come, probably. Still need to figure out the best way to only construct a new `Twitter` object when *necessary*.
> Update to use tweety-ns version 0.9

- sopel_twitter/__init__.py
What it says on the tin. If we're using user+pass login now, and that method can raise this error, then it must be handled.
There isn't much the code can do to recover if it happens, but at least Sopel won't spit out an unexpected-error line.
> Handle new DeniedLogin exception type

- sopel_twitter/__init__.py
Tweety's documentation doesn't say anything about `Optional` or `| None` for these `User` fields, so the previous code could throw an error if any of the four expected-to-be-`int` profile values was 0—which is converted to `None` for some reason.\*
Note: Only ran into the case where favorites would be `None`, but `User` object code upstream sets all of these the same way so let's just make sure they're all safely handled.
(Fortunately it appears that Xitter doesn't allow empty `user.name`.)
_\* — Presumably the reverse-engineered JSON endpoint(s) Tweety uses just _don't send_ those `int` fields at all for values of `0`, so the `User` object defaults to `None` for them when it's setting itself up._
> Band-aid fix for int fields in user that can be `None`

- sopel_twitter/__init__.py
Xitter has begun yielding x.com links when the Share button is used.
Rejected idea that came up when writing this patch: Handling `www.` prefix on all domains, in addition to `m.` and `mobile.` (which also do work with `x.com`; I tested them).
> Handle x.com links by default

- sopel_twitter/__init__.py
The configuration setting does not expect regular expressions. It's best practice to escape the `.` in a domain as `\.` when using it in a regex. Use of `re.escape()` was just forgotten when the `alternate_domains` setting got implemented.
> Escape extra domains when lazily building URL patterns

- sopel_twitter/__init__.py
Previous fix (#54) didn't work; `type(None) is not None`.
Checking `type()` was wholly unnecessary.
> Handle nullable `int` fields in `User`, for real this time

- setup.cfg
Quick tests show that it still just works, and the changelog upstream only mentions added methods. Not that that means there aren't removals or changes (upstream docs are... not great), but I would prefer to just allow the newer library and deal with breakage if/when it surfaces.
> Bump to newer Tweety library, 1.0.x

- sopel_twitter/__init__.py
Shorter companion to vxtwitter.com, run by the same person on the same forked software stack.
> Add fixvx.com to default alternate domains

- sopel_twitter/__init__.py
This didn't actually take as long as I thought it might. Starting to think those `truncation` and `trailing` args to `bot.say()` really were brilliant (but I can't say that because they were my idea 😁).
Compare 1.3.6 (Yuzu) to this patch (SopelTest):
> 13:33:41 <~dgw> https://twitter.com/Spicy_Wolf_Prj/status/1767128338525753842
>
> 13:33:42 <&Yuzu> [Twitter] 『狼と香辛料』🍎4月1日(月)25:30よりテレ東ほかにて放送！ (@Spicy_Wolf_Prj): .｡.:✽・ﾟ ⏎ 初回放送4月1日(月)25:30より ⏎ テレ東ほかにて放送決定 ⏎ .｡.:✽・ﾟ ⏎ 放送情報詳細はこちら🔽 ⏎ https://spice-and-wolf.com/onair/ ⏎ 更に、今週3月17日(日)は先行上映会‼️ ⏎ ご好評につき、3月13日(水)0時より、 ⏎ 新宿・梅田のチケットが発売開始🎫
>
> 13:33:43 \<SopelTest> [Twitter] 『狼と香辛料』🍎4月1日(月)25:30よりテレ東ほかにて放送！ (@Spicy_Wolf_Prj): .｡.:✽・ﾟ ⏎ 初回放送4月1日(月)25:30より ⏎ テレ東ほかにて放送決定 ⏎ .｡.:✽・ﾟ ⏎ 放送情報詳細はこちら🔽 ⏎ https://spice-and-wolf.com/onair/ ⏎ 更に、今週3月17日(日)は先行上映会‼️ ⏎ …
> Perform graceful truncation of overly long tweet text

- pyproject.toml
For the next non-patch release of this plugin, the upper version bound should probably be removed. Users can most likely downgrade `tweety-ns` themselves if a newer version causes problems, but they'll have trouble installing a newer version if an older one stops working.
The same non-patch release should drop Sopel<8, which somewhat dictates its timing (NET Sopel 8.0 stable release).
> Bump Tweety to 1.1.x

- pyproject.toml
- sopel_twitter/__init__.py
Minimum `tweety-ns` version is now 1.1.4, the version in which this new attribute was added.
This might reduce #62, but the real fix will be updated exception handling.
> Use new `is_user_authorized` attribute to check session state

- sopel_twitter/__init__.py
The plugin used to do this, but it got lost when adding graceful truncation in f1db7fd76c85a8390bb629790981c82d06fa6ffa (#61).
> Add "Quoting" to output, disambiguating which tweet was quoted

- sopel_twitter/__init__.py
Documentation implies that you have to run `app.connect()` to reuse an existing saved session, but `app.sign_in()` calls the `connect()` method internally if the session exists and matches the passed-in `username`.
This behavior should already exist in the plugin's current minimum `tweety-ns` version of 1.1.4, based on commit dates. Upstream doesn't maintain tags or other version metadata within the source repository, though, so this is just me taking an educated guess.
Goal of this patch is to prevent the issue I just ran into, where the plugin said its credentials were invalid but the _actual_ problem was an expired session from several months ago. My test-account's username & password were fine.
> Trust the `sign_in()` method
